version: 2
# Individual jobs, using sleep to mock a longer running process
jobs:
  one:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: setup dependencies
          command: 'yarn'
      - run:
          name: Running tests
          command: yarn test --runInBand
      - run: echo "tests complete"
      - store_test_results:
          path: ./

# Must excplicitly list the jobs to be run
workflows:
  version: 2
  one:
    jobs:
      - one
