version: 2
# Individual jobs, using sleep to mock a longer running process
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: yarn test
      - run: echo "tests complete"
  # two:
  #   docker:
  #     - image: circleci/ruby:2.4.1-jessie
  #   steps:
  #     - checkout
  #     - run: echo "A 2nd hello"
  #     - run: sleep 15
# Must excplicitly list the jobs to be run
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      # - two
